site_name: nteract
repo_url: https://github.com/nteract/nteract
repo_name: "GitHub"

nav:
  - Home: "index.md"
  - Packages:
      - "@nteract/actions": "!include ./packages/actions/mkdocs.yml"
      - "@nteract/stateful-components": "!include ./packages/stateful-components/mkdocs.yml"

plugins:
  - monorepo

theme:
  name: gitbook
