site_name: nteract
repo_url: https://github.com/nteract/nteract
repo_name: "GitHub"

nav:
  - Packages:
      - "@nteract/stateful-components": "!include ./packages/stateful-components/mkdocs.yml"

plugins:
  - monorepo
